# Generated by Django 4.2.2 on 2023-06-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hls_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Default Name', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default='Default File', upload_to='movies/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
