# Generated by Django 4.2.2 on 2023-06-06 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='file',
            new_name='hls_file_url',
        ),
    ]
