# Generated by Django 4.2.2 on 2023-06-06 21:21

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_file_movie_hls_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='hls_file_url',
            field=models.FileField(upload_to=movies.models.movie_directory_path),
        ),
    ]
